name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: ['gcc', 'clang']
        exclude:
          - os: macos-latest
            compiler: gcc  # gcc is clang on macOS

    runs-on: ${{ matrix.os }}

    env:
        CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v4
    - name: Log compiler version
      run: |
        "$CC" --version
    - name: make test    # unit tests
      run: make test
<<<<<<< HEAD
    - name: "macOS: brew install gmp"
      if: runner.os == 'macOS'
      run: brew install gmp
=======
    # TODO(creachadair): As of 25-Jan-2024, the GMP compatibility tests
    # on gcc no longer work correctly when run in containers either
    # locally or in github actions. They work fine from the CLI, but
    # for now turn them off in CI.
>>>>>>> 4b28544 (Update .github/workflows/unit-tests.yml)
    - name: make check   # unit and compatibility tests
      if: matrix.compiler == 'clang'
      run: make check
